### ISSUE TITLE
Loading VN saved game from VN template produces duplicate portraits

### ISSUE THREAD

**Issue by metanoder** [Dialogic-Godot/Dialogic-Test-Project#13]
## The problem
Saved games loaded from VN template Main Menu will have duplicate portraits within each portrait container.  
Duplicate portraits remain in portrait container even after --leave all-- is called.

**To Reproduce**
1. Start new game.
2. Play till there is a character portrait present.
3. Save
4. Reload / restart / exit to main menu ( this is to simulate a fresh game session )
5. Load saved game 
6. Check remote scene tree : root/VN_PortraitLayer/Portraits/...

**Expected behavior**
Loading saved games, portrait containers only have intended character within without additional instance of the same character present.  This leads to unwanted behaviors and character portraits hanging within.  

**Screenshots**
![dialogic_template_bug_report](https://github.com/dialogic-godot/test-project/assets/117393840/92e6828b-7021-4f2e-bde2-1b084919fd6f)

**System:**
 - OS: Windows
 - Godot Version: 4.2.2
 - Dialogic Version: latest: Dialogic 2.0 - Alpha 13 [b14d635](https://github.com/dialogic-godot/dialogic/commit/b14d635082ac67fc7f60ddd6a2cf2d63cd5d401e)

## Solutions

**Workaround**
Starting new game, then load from submenu yields expected results.

**What you tried to get the feature working**
Tried manually gathering children after saved file slot loaded, and queue freeing the duplicates.  Failed.  In production project, only one duplicate queued free out of 2-3 duplicates.

**Comment by CTZFET** [comment]
I MEET IT TOO, I TRY FIX IT BUT IT CANT WORK, I FEEL BAD

**Comment by metanoder** [comment]
> I MEET IT TOO, I TRY FIX IT BUT IT CANT WORK, I FEEL BAD

The template's addon just needs to be updated.

delete:
VN_template/addons/dialogic

download the latest repo:
git clone https://github.com/dialogic-godot/dialogic.git

update template addons folder:
Dialogic/addons/dialogic -> VN_template/addons/dialogic

**Comment by metanoder** [comment]
Bug still present after testing with the latest repo update.

**Comment by Jowan-Spooner** [comment]
This should be fixed now by the alpha 15 WIP update.

**Comment by metanoder** [comment]
Thank you!
